[package]
name = "user_manage"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "22.2.0"
bcrypt="0.13"
lazy_static="1.4.0"
rand = "0.8.5"